### ISSUE TITLE
JsonWriter flush doesn't flush?

### ISSUE THREAD

**Issue by lfdversluis** [avaje/avaje-jsonb#123]
Hi, if I run the following code I am not getting any output on my print. Only after I close the JsonWriter I get output in the writer, which is undesired. This looks like a bug to me. https://avaje.io/apidocs/avaje-jsonb/io/avaje/jsonb/JsonWriter.html#flush() says it should flush the writer.
```
public static void main(String[] args) {
        CharArrayWriter writer = new CharArrayWriter();
        var jsonWriter = JsonStream.builder().serializeNulls(true).build().writer(writer);

        jsonWriter.value("test");
        jsonWriter.flush();
//        jsonWriter.close();
        System.out.println(writer.toCharArray());
    }
```

**Comment by rbygrave** [comment]
Yes. The code was not flushing the underlying writer until `close()`.  The PR adds the test for this and fix to move the underlying flush().

Releasing 1.6-RC3 now which contains this fix.
