### ISSUE TITLE
[enhancement] Add support for @Json.Property on instance methods

### ISSUE THREAD

**Issue by Mechite** [avaje/avaje-jsonb#174]
`@Json.Property` is currently not applicable to methods while e.g., Jackson supports this feature.

This is to be avoided on e.g., accessor methods, because jsonb is able to resolve these automatically, but this is useful if computation is required for a given method to provide a more suitable representation during serialization.

I personally had a use for this for certain DTOs delegating other objects and not serializing them completely, but it would be useful in many other cases.

Perhaps if you would like to conventionalize the avoidance of this feature (so people don't just put it on their accessor methods, i.e. getters setters), you could create a new annotation `@Json.Computed` for this purpose, and specifically state in the documentation that it is to be avoided (I've been told there was a reason that this feature was omitted from avaje-jsonb).

In every case I've had a use for this method, it would not have been useful for **deserialization** - the property is to be completely ignored and only when serializing, run to retrieve a computed value.

CC @SentryMan

**Comment by rob-bygrave** [comment]
> @Json.Property on instance methods

It would not really be valid to put it on a setter method, but a getter/accessor should be ok.

Note that avaje-jsonb didn't originally support interfaces in terms of "deserialisation only" but it does now. This seems related in that the deserialisation of interfaces is based on getter/accessors (no use of fields). So in that sense it seems reasonable to expect a `@Json.Property` to be used there.
