### ISSUE TITLE
Unable to generate an adapter from a wrapper around ArrayList

### ISSUE THREAD

**Issue by YongSa** [avaje/avaje-jsonb#194]
I have a Class with nothing in it's class body that basically just wraps ArrayList like so:
`public class Customers extends ArrayList<Costumer>`
When trying to generate an adapter for this, the compileJava step fails with the following error: 

> Non public field com.company.project.folder.Customers size with no matching setter or constructor?

Am I missing something or is this not supported?

**Comment by SentryMan** [comment]
That's not gonna serialize properly yeah. It's not a good idea to extend the built-in java collections regardless.

If you have some logic you want to isolate in a collection class, I would suggest the below solution:
```java
public class Costumer {

    ArrayList<Costumer> costumer;

    public Costumer newMethod() {
       // ... your logic goes here.
    }
}
```
