### ISSUE TITLE
(Feature-Request) Case-insensitive Deserialization Option

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-jsonb#44]
Would be nice to have something like that

**Comment by rbygrave** [comment]
Meaning that the keys are case-insensitive?  e.g. given a property called `Name` then json with keys of `Name`, `name`, `NAME`, `NaMe` etc ... would all be deserialised to this property.

Implementation something like - lower case of the deserialised key is equal to the lower cased key.

**Comment by rbygrave** [comment]
This would be on the class level, so ALL properties of that type would use case-insensitive key matching right?

**Comment by SentryMan** [comment]
> This would be on the class level, so ALL properties of that type would use case-insensitive key matching right (so NOT on a per property basis)?

yeah something like that.

**Comment by rbygrave** [comment]
I'll release version `1.1-RC2` with this in it.
