### ISSUE TITLE
No longer compiles to Java 8 (Time to upgrade?)

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-jsonb#57]
Since we added that inject plugin, the project no longer compiles to java 8. I notice also the github actions doesn't even have 8 anymore.

**Comment by rbygrave** [comment]
I would have gone with 11 originally except the java-json-benchmark uses Java 8. Looks like there is a plan to move it to 17 though - https://github.com/fabienrenaud/java-json-benchmark/pull/60/files

I think we can go to 11, the benchmark can just use version 1.1 until it upgrades to 17 etc.
