### ISSUE TITLE
v1.2: GeneratedComponent duplicates builder.add calls for the same adapters

### ISSUE THREAD

**Issue by LoonyRules** [avaje/avaje-jsonb#60]
If you have a package that has 2 different classes that use the same class you have your `@Json` annotation on, the GeneratedJsonComponent class will have 2 `builder.add(..., ...)` method calls.

This causes the `@MetaData(...)` annotation on the class to have the same adapter defined too.

Another thing I noticed during this duplicated builder.add method call, is that in `v1.2-RC3`, the generated class is generated fine:
```java
@Generated
@MetaData({ProbeStateJsonAdapter.class, ProbeStateJsonAdapter.class})
public class GeneratedJsonComponent implements Jsonb.GeneratedComponent {

  @Override
  public void register(Jsonb.Builder builder) {
    builder.add(ProbeState.class, ProbeStateJsonAdapter::new);
    builder.add(ProbeState.class, ProbeStateJsonAdapter::new);
  }

}
```
However, in `v1.2` the generated class is not fine:
 ```java
 @Generated
@MetaData({Prob.class, ProbeStateJsonAdapter.class})
public class GeneratedJsonComponent implements Jsonb.GeneratedComponent {

  @Override
  public void register(Jsonb.Builder builder) {
    // This is wrong, Prob.class and ProbeStateJsonA.class do not exist, it's like the generation broke since the RC3 and the actual release.
    builder.add(Prob.class, ProbeStateJsonA::new);
    builder.add(ProbeState.class, ProbeStateJsonAdapter::new);
  }

}
```

**Comment by LoonyRules** [comment]
Update: This might be specific to running the application inside of IntelliJ as I am not able to reproduce if running directly via the java cli. The issue isn't present when running inside of IntelliJ when using v1.2-RC3 though, that could just be a fortunate cache (even though I have invalidated them all). Going to do more digging :)

**Comment by LoonyRules** [comment]
I can't see anything obvious. One thing to mention is that IntelliJ will recompile some modules when you run/debug inside of IntelliJ. Is this step that causes the `GeneratedJsonComponent` to be generated incorrectly.

If you `mvn clean package` or `mvn clean install` separately, everything is fine. Perhaps some edge-case was missed in the Prism addition?

No idea, but good luck @SentryMan 😅

**Comment by SentryMan** [comment]
>Perhaps some edge-case was missed in the Prism addition? 

It seems so

**Comment by rbygrave** [comment]
Looking to release 1.3-RC3 with #65 merged ... so we can look to confirm if that fixes it.

**Comment by SentryMan** [comment]
I think we're good with this, he messaged me and said it seems to work now

**Comment by LoonyRules** [comment]
Closing as it has fixed the issue.
